### PR TITLE
Update for NEP

### PR DESCRIPTION
**Pull request by mikemhenry**
Drop python 3.7 from testing matrxi and add python 3.10, using quotes to avoid [yaml parsing issues](https://dev.to/hugovk/the-python-3-1-problem-85g)

### CODE REVIEW

**Comment by janash** [comment]
@Lnaden - Considering that Python 3.10 is the standard on the docs, I think we should merge this.

**Comment by janash** [comment]
Ah, right. Yes, the appropriate file needs to be changed.

**Comment by mikemhenry** [comment]
Does everything in `github/reference-workflows/*` need to be fixed as well? Now I have updated the template.

**Comment by Lnaden** [comment]
Yes. The template file needed to be updated, and the references can be regenerated with https://github.com/MolSSI/cookiecutter-cms/blob/master/tests/regenerate_references.sh no need to do it by hand (in fact dont do it by hand)

**Comment by mikemhenry** [comment]
@Lnaden That should do it, I think you have to approve CI to run since this is my first time contributing to the repo.

**Review by Lnaden — APPROVED** [review]

**Pull request merged**
