### PR TITLE
Fix import sorting in test file

### PR DESCRIPTION
**Pull request by radifar**
The imports need to be sorted in order to follow [PEP 8 style](https://www.python.org/dev/peps/pep-0008/#imports). I also confirm this change with [isort](https://github.com/PyCQA/isort).

### CODE REVIEW

**Comment by Lnaden** [comment]
This is an interesting proposition. I'd put another blank between the `pytest` and the cookiecutter output to adhere to points 2 and 3 + blank line of: 

> Imports should be grouped in the following order:
> 
> * Standard library imports.
> * Related third party imports.
> * Local application/library specific imports.
> You should put a blank line between each group of imports.

**Comment by radifar** [comment]
That is also what I thought at first, but then if I use this cookiecutter and use `example-project` as the name, then I would have the following import:
```python
import example_project
import pytest
import sys
```
and after it is getting sorted with isort the result will be the following
```python
import sys

import example_project
import pytest
```
After pondering about it, it does make sense because test can be seen as separate code from the `example-project` package and in the eye of the test code `example-project` is third-party library. Also notice that local library is imported via relative location import such as `import .functions`.

**Comment by Lnaden** [comment]
The local library can be imported via relative imports or absolute in modern Pythons. I can never remember which is supposed to be used and it so rarely causes a problem it almost never maters (if you're doing dev work and have a package with the same name or open your python interpreter in a folder with a package you're trying to import such as during CI.) I think it might be okay to ignore the 3rd point since packages like `isort` cannot figure out if the package is local or not. 

This does bring up the question though of how to handle package names and the order. If we build in the 3rd point and just add the space, then we don't have to worry about the order of "3rd party/local" packages. We could do something needlessly complicated and try to figure out the sort at cookiecutter runtime, but that's likely going to cause more problems in search of the solution of a user following up if they so choose.

Thinking on it now, I feel adhering to the PEP8 standard and move the local package name to a 3rd grouping with a line space is technically correct and the most clear, let packages like `isort` and other formatters do whatever after that.

**Comment by radifar** [comment]
> Thinking on it now, I feel adhering to the PEP8 standard and move the local package name to a 3rd grouping with a line space is technically correct and the most clear, let packages like isort and other formatters do whatever after that.

Yes, I agree it is certainly most clear that way. I'll add another commit for this.

**Review by Lnaden — APPROVED** [review]
LGTM

**Pull request merged**
