### PR TITLE
Improve PEP-257 compliance.

### LINKED ISSUE #130: Templated docstring should follow PEP257 conventions.
The templated docstring is not consistent with PEP257:
https://github.com/MolSSI/cookiecutter-cms/blob/fb218d02b2cb846862d7f175c8e9e82d58d3a195/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.first_module_name%7D%7D.py#L2

If this is intentional (such as for the workshop participant to correct during an exercise), maybe this could be clarified or made static instead of using the template.

Otherwise:
- [ ] Put a blank line between the first and second line.
- [ ] Use the first line for a concise description according to PEP257 and numpy docstring conventions that will look good when formatted with `pydoc` or `help()`. This could mean just removing the `molecool\n` first line.

### PR DESCRIPTION
**Pull request by eirrgang**
Add some line breaks and make complete sentences.

Fixes #130.

### CODE REVIEW

**Review by Lnaden — APPROVED** [review]
LGTM

**Comment by Lnaden** [comment]
Is this ready to go?

**Comment by eirrgang** [comment]
> Is this ready to go?

Yes. Sorry. I think that second commit is an improvement, but I think this is it unless changes are requested.

**Comment by Lnaden** [comment]
None needed, looks good to me

**Pull request merged**
