### PR TITLE
Bump Python to 3.8 and 3.9

### PR DESCRIPTION
**Pull request by Lnaden**
Increase Python version to 3.8 and 3.9.

Replacement for #119 now that AppVeyor and Travis are dropped.

### CODE REVIEW

**Comment by jchodera** [comment]
@lnaden: Is it wise to _drop_ CI for 3.7? 

The [policy for conda-forge](https://conda-forge.org/docs/orga/guidelines.html#python), for example, is 
"For the Python language, conda-forge aims to keep package builds active and available for the current version and at least two preceding minor versions."

Shouldn't we do the same here?

**Comment by Lnaden** [comment]
We've only ever held the most recent and 1 previous version of Python minor (+2.7 when it mattered). A few reasons for that:

1. It cut back on the CI testing we had to do, which was much more taxing back when supporting 2.7.
2. It ensures we can test the most recent versions quickly.
3. As I recall, we were following the CF guidelines of the 2 most recent + 2.7, which may have been changed with the drop of 2.7, but I could simply be misremembering.
4. It hasn't been an issue mainly because we have no need to incorporate some of the newer features for this project which would not be backwards compatibles. f-strings might be the most feature-rich thing we use here which may not port all the way back.

I'm happy to reconsider. What do others think?

**Comment by janash** [comment]
Thanks @jchodera for pointing this out. 

@Lnaden - my opinion - Since this cookiecutter is intended to start users on projects which will hopefully be deployed (a likely place being conda-forge), I think it makes sense to follow them on our supported Python versions. As @jchodera pointed out, this would be to keep the current version and two preceding minor versions.

**Comment by jchodera** [comment]
@lnaden: f-strings were introduced in Python 3.6, so that shouldn't be a concern here.

**Pull request merged**
